# Generated by Django 2.1 on 2018-11-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigoCliente', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('fec_nac', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('ciudad', models.CharField(blank=True, max_length=30)),
                ('tipo_vivienda', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMascota', models.CharField(max_length=20)),
                ('razaMascota', models.CharField(max_length=20)),
                ('descripcionMascota', models.CharField(max_length=50)),
                ('estadoMascota', models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('rescatado', 'Rescatado')], default='', max_length=15, verbose_name='estadoMascota')),
                ('fotoMascota', models.ImageField(upload_to='Sistema/static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FRONT.Cliente')),
                ('codigoMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FRONT.Mascota')),
            ],
        ),
    ]
